### ISSUE TITLE
스타일 변수명에 대해서

### ISSUE THREAD

**Issue by chanwukim** [oduck-team/oduck-client#132]
## 📝 개요
ui 라이브러리를 많이 참고해보니 `variant`라는 변수명을 많이 사용하고 있더라구요
저희는 `styleType`으로 사용하고있는데, 대중화된 스타일을 위해 `variant`로 변경 어떤지 논의입니다

**Comment by imdaxsz** [comment]
바꾸는 게 좋을 것 같네요!
