### ISSUE TITLE
컴포넌트 파일 구조(파일 묶기 및 분리)를 변경한다.

### ISSUE THREAD

**Issue by presentKey** [oduck-team/oduck-client#172]
## 📝 개요
컴포넌트 파일 구조(파일 묶기 및 분리)를 변경한다.

| 기존 | 변경 |
| :---: | :---: |
|![image](https://github.com/oduck-team/oduck-client/assets/115006670/fc5dc95e-779f-40ed-910c-36200ce478b5) | ![image](https://github.com/oduck-team/oduck-client/assets/115006670/df2c8878-7203-4b40-a434-e78c5ffeefe7) | 

-----

### - 경로 `users > routes > Profile > index.tsx`
index.tsx 컴포넌트가 `AboutMe` `ReviewList` 하위 컴포넌트를 가질때
```tsx
export default function Profile() {
  return (
    <Container>
      <AboutMe />
      <ReviewList />
    </Container>
  );
}
```

AboutMe, ReviewList 폴더를 생성하고, 해당 폴더는 이 컴포넌트에 관련된 파일들을 관리합니다.

![image](https://github.com/oduck-team/oduck-client/assets/115006670/e28abcd1-88f8-46a7-a2bf-8ac765c5e8eb)

-----

### - 경로 `users > components` 
components 폴더는 routes에서 재사용되는 컴포넌트이거나, user에 관한 공용 컴포넌트를 관리하는 폴더입니다.

공용 컴포넌트명 폴더를 생성하고, 해당 폴더는 이 컴포넌트에 관련된 파일들을 관리합니다.

![image](https://github.com/oduck-team/oduck-client/assets/115006670/4b8db222-4283-4c6f-b0b2-ba15d38f3be3)

## ✅ TODO
- [x] 컴포넌트 파일 구조를 변경한다.
   - [x] @imdaxsz 
   - [x] @a-ryang 
   - [x] @presentKey

**Comment by chanwukim** [comment]
애니 상세는 아직 퍼블리싱 완료 전이라 수정할게 없네요
